sudo: false
dist: precise
language: ruby
rvm:
  - 2.3.4
before_install: gem install bundler
cache:
  - bundler
  - apt
services:
  - mysql
env:
  global:
    - ARMG_TEST_MYSQL_PORT=3306
script:
  - bundle exec rake
